## PreProcessing

In [1]:
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [5]:
X,y = load_iris(return_X_y=True)

In [6]:
X_train , X_test , y_train,y_test = train_test_split(X,y,test_size=0.2)

### Standard Scaling

In [7]:
scalar = StandardScaler()

X_train_scaled = scalar.fit_transform(X_train)
X_test_scaled = scalar.transform(X_test)

In [9]:
X_train_scaled

array([[ 1.53313974, -0.19753737,  1.09206835,  0.45629685],
       [-1.04323767, -2.47681468, -0.18455539, -0.31310299],
       [ 2.11868007,  1.62588448,  1.59161677,  1.2256967 ],
       [ 0.47916716, -1.33717602,  0.59251993,  0.32806354],
       [-0.34058929, -0.19753737,  0.14847689,  0.07159693],
       [ 2.11868007, -1.10924829,  1.70262753,  1.35393   ],
       [ 0.47916716,  0.71417356,  0.98105759,  1.48216331],
       [ 0.59627523, -0.65339283,  0.98105759,  1.2256967 ],
       [ 1.65024781, -0.4254651 ,  1.36959525,  0.71276347],
       [-1.39456187,  0.2583181 , -1.40567375, -1.33896945],
       [ 0.47916716,  0.48624583,  0.48150917,  0.45629685],
       [-0.57480542,  0.71417356, -1.29466299, -1.08250284],
       [-0.34058929, -0.88132056,  0.20398227,  0.07159693],
       [ 0.12784297,  0.71417356,  0.37049841,  0.45629685],
       [-0.92612961,  1.39795675, -1.29466299, -1.08250284],
       [-0.10637316, -0.88132056,  0.70353069,  0.84099677],
       [-0.10637316,  2.

### Manual Standard Scaling

In [16]:
import numpy as np

(X_train - np.mean(X_train,axis=0))/np.std(X_train,axis=0)

array([[ 1.53313974, -0.19753737,  1.09206835,  0.45629685],
       [-1.04323767, -2.47681468, -0.18455539, -0.31310299],
       [ 2.11868007,  1.62588448,  1.59161677,  1.2256967 ],
       [ 0.47916716, -1.33717602,  0.59251993,  0.32806354],
       [-0.34058929, -0.19753737,  0.14847689,  0.07159693],
       [ 2.11868007, -1.10924829,  1.70262753,  1.35393   ],
       [ 0.47916716,  0.71417356,  0.98105759,  1.48216331],
       [ 0.59627523, -0.65339283,  0.98105759,  1.2256967 ],
       [ 1.65024781, -0.4254651 ,  1.36959525,  0.71276347],
       [-1.39456187,  0.2583181 , -1.40567375, -1.33896945],
       [ 0.47916716,  0.48624583,  0.48150917,  0.45629685],
       [-0.57480542,  0.71417356, -1.29466299, -1.08250284],
       [-0.34058929, -0.88132056,  0.20398227,  0.07159693],
       [ 0.12784297,  0.71417356,  0.37049841,  0.45629685],
       [-0.92612961,  1.39795675, -1.29466299, -1.08250284],
       [-0.10637316, -0.88132056,  0.70353069,  0.84099677],
       [-0.10637316,  2.

---
### Min-Max Scaling

In [15]:
from sklearn.preprocessing import MinMaxScaler

scaler_min_max = MinMaxScaler()

X_train_scaled_minmax = scaler_min_max.fit_transform(X_train)
X_test_scaled_minmax = scaler_min_max.transform(X_test)

X_train_scaled_minmax

array([[0.80555556, 0.41666667, 0.81355932, 0.625     ],
       [0.19444444, 0.        , 0.42372881, 0.375     ],
       [0.94444444, 0.75      , 0.96610169, 0.875     ],
       [0.55555556, 0.20833333, 0.66101695, 0.58333333],
       [0.36111111, 0.41666667, 0.52542373, 0.5       ],
       [0.94444444, 0.25      , 1.        , 0.91666667],
       [0.55555556, 0.58333333, 0.77966102, 0.95833333],
       [0.58333333, 0.33333333, 0.77966102, 0.875     ],
       [0.83333333, 0.375     , 0.89830508, 0.70833333],
       [0.11111111, 0.5       , 0.05084746, 0.04166667],
       [0.55555556, 0.54166667, 0.62711864, 0.625     ],
       [0.30555556, 0.58333333, 0.08474576, 0.125     ],
       [0.36111111, 0.29166667, 0.54237288, 0.5       ],
       [0.47222222, 0.58333333, 0.59322034, 0.625     ],
       [0.22222222, 0.70833333, 0.08474576, 0.125     ],
       [0.41666667, 0.29166667, 0.69491525, 0.75      ],
       [0.41666667, 0.83333333, 0.03389831, 0.04166667],
       [0.66666667, 0.45833333,

### Manual MinMax Scaling

In [17]:
X_min = np.min(X_train,axis = 0)
X_max = np.max(X_train,axis = 0)

(X_train-X_min)/(X_max - X_min)

array([[0.80555556, 0.41666667, 0.81355932, 0.625     ],
       [0.19444444, 0.        , 0.42372881, 0.375     ],
       [0.94444444, 0.75      , 0.96610169, 0.875     ],
       [0.55555556, 0.20833333, 0.66101695, 0.58333333],
       [0.36111111, 0.41666667, 0.52542373, 0.5       ],
       [0.94444444, 0.25      , 1.        , 0.91666667],
       [0.55555556, 0.58333333, 0.77966102, 0.95833333],
       [0.58333333, 0.33333333, 0.77966102, 0.875     ],
       [0.83333333, 0.375     , 0.89830508, 0.70833333],
       [0.11111111, 0.5       , 0.05084746, 0.04166667],
       [0.55555556, 0.54166667, 0.62711864, 0.625     ],
       [0.30555556, 0.58333333, 0.08474576, 0.125     ],
       [0.36111111, 0.29166667, 0.54237288, 0.5       ],
       [0.47222222, 0.58333333, 0.59322034, 0.625     ],
       [0.22222222, 0.70833333, 0.08474576, 0.125     ],
       [0.41666667, 0.29166667, 0.69491525, 0.75      ],
       [0.41666667, 0.83333333, 0.03389831, 0.04166667],
       [0.66666667, 0.45833333,

---
## Feature Decoding

---
### Ordinal Decoding : 
When there is progression and we can order it as 1,2,3

In [18]:
from sklearn.datasets import fetch_openml
from sklearn.preprocessing import OrdinalEncoder

In [19]:
data = fetch_openml('car',as_frame=True).frame

c:\Users\OMEN\OneDrive\Desktop\Machine Learning\.venv\Lib\site-packages\sklearn\datasets\_openml.py:324: UserWarning: Multiple active versions of the dataset matching the name car exist. Versions may be fundamentally different, returning version 2. Available versions:
- version 2, status: active
  url: https://www.openml.org/search?type=data&id=991
- version 3, status: active
  url: https://www.openml.org/search?type=data&id=40975

  warn(warning_msg)


In [20]:
data

buying  maint  doors persons lug_boot safety binaryClass
0     vhigh  vhigh      2       2    small    low           P
1     vhigh  vhigh      2       2    small    med           P
2     vhigh  vhigh      2       2    small   high           P
3     vhigh  vhigh      2       2      med    low           P
4     vhigh  vhigh      2       2      med    med           P
...     ...    ...    ...     ...      ...    ...         ...
1723    low    low  5more    more      med    med           N
1724    low    low  5more    more      med   high           N
1725    low    low  5more    more      big    low           P
1726    low    low  5more    more      big    med           N
1727    low    low  5more    more      big   high           N

[1728 rows x 7 columns]

In [22]:
columns_to_encode = ['lug_boot','safety']

encoder = OrdinalEncoder(
    categories=[
        ['small','med','big'],
        ['low','med','high']
    ]
)

data[columns_to_encode] = encoder.fit_transform(data[columns_to_encode])

In [23]:
data

buying  maint  doors persons  lug_boot  safety binaryClass
0     vhigh  vhigh      2       2       0.0     0.0           P
1     vhigh  vhigh      2       2       0.0     1.0           P
2     vhigh  vhigh      2       2       0.0     2.0           P
3     vhigh  vhigh      2       2       1.0     0.0           P
4     vhigh  vhigh      2       2       1.0     1.0           P
...     ...    ...    ...     ...       ...     ...         ...
1723    low    low  5more    more       1.0     1.0           N
1724    low    low  5more    more       1.0     2.0           N
1725    low    low  5more    more       2.0     0.0           P
1726    low    low  5more    more       2.0     1.0           N
1727    low    low  5more    more       2.0     2.0           N

[1728 rows x 7 columns]

In [ ]:
encoder.inverse_transform(data[columns_to_encode]) # To reverse encoding

---
### One hot encoder
When no progression as categorical attributes

In [25]:
data2 = fetch_openml('adult',as_frame=True).frame

c:\Users\OMEN\OneDrive\Desktop\Machine Learning\.venv\Lib\site-packages\sklearn\datasets\_openml.py:324: UserWarning: Multiple active versions of the dataset matching the name adult exist. Versions may be fundamentally different, returning version 1. Available versions:
- version 1, status: active
  url: https://www.openml.org/search?type=data&id=179
- version 2, status: active
  url: https://www.openml.org/search?type=data&id=1590

  warn(warning_msg)


In [26]:
data2

age         workclass  fnlwgt  education  education-num  \
0       2         State-gov   77516  Bachelors             13   
1       3  Self-emp-not-inc   83311  Bachelors             13   
2       2           Private  215646    HS-grad              9   
3       3           Private  234721       11th              7   
4       1           Private  338409  Bachelors             13   
...    ..               ...     ...        ...            ...   
48837   2           Private  215419  Bachelors             13   
48838   4               NaN  321403    HS-grad              9   
48839   2           Private  374983  Bachelors             13   
48840   2           Private   83891  Bachelors             13   
48841   1      Self-emp-inc  182148  Bachelors             13   

           marital-status         occupation    relationship  \
0           Never-married       Adm-clerical   Not-in-family   
1      Married-civ-spouse    Exec-managerial         Husband   
2                Divorced  Handlers-cleaners   Not-in-family   
3      Married-civ-spouse  Handlers-cleaners         Husband   
4      Married-civ-spouse     Prof-specialty            Wife   
...                   ...                ...             ...   
48837            Divorced     Prof-specialty   Not-in-family   
48838             Widowed                NaN  Other-relative   
48839  Married-civ-spouse     Prof-specialty         Husband   
48840            Divorced       Adm-clerical       Own-child   
48841  Married-civ-spouse    Exec-managerial         Husband   

                     race     sex capitalgain capitalloss hoursperweek  \
0                   White    Male           1           0            2   
1                   White    Male           0           0            0   
2                   White    Male           0           0            2   
3                   Black    Male           0           0            2   
4                   Black  Female           0           0            2   
...                   ...     ...         ...         ...          ...   
48837               White  Female           0           0            2   
48838               Black    Male           0           0            2   
48839               White    Male           0           0            3   
48840  Asian-Pac-Islander    Male           2           0            2   
48841               White    Male           0           0            3   

      native-country  class  
0      United-States  <=50K  
1      United-States  <=50K  
2      United-States  <=50K  
3      United-States  <=50K  
4               Cuba  <=50K  
...              ...    ...  
48837  United-States  <=50K  
48838  United-States  <=50K  
48839  United-States  <=50K  
48840  United-States  <=50K  
48841  United-States   >50K  

[48842 rows x 15 columns]

In [27]:
from sklearn.preprocessing import OneHotEncoder

In [ ]:
data.occupation.value_counts()

occupation
Prof-specialty       6172
Craft-repair         6112
Exec-managerial      6086
Adm-clerical         5611
Sales                5504
Other-service        4923
Machine-op-inspct    3022
Transport-moving     2355
Handlers-cleaners    2072
Farming-fishing      1490
Tech-support         1446
Protective-serv       983
Priv-house-serv       242
Armed-Forces           15
Name: count, dtype: int64

In [29]:
import pandas as pd

encoder = OneHotEncoder(handle_unknown='ignore',sparse_output=False)
encoded_values = encoder.fit_transform(data[['occupation','race']])
new_cols = encoder.get_feature_names_out(['occupation','race'])

In [30]:
new_cols

array(['occupation_Adm-clerical', 'occupation_Armed-Forces',
       'occupation_Craft-repair', 'occupation_Exec-managerial',
       'occupation_Farming-fishing', 'occupation_Handlers-cleaners',
       'occupation_Machine-op-inspct', 'occupation_Other-service',
       'occupation_Priv-house-serv', 'occupation_Prof-specialty',
       'occupation_Protective-serv', 'occupation_Sales',
       'occupation_Tech-support', 'occupation_Transport-moving',
       'occupation_nan', 'race_Amer-Indian-Eskimo',
       'race_Asian-Pac-Islander', 'race_Black', 'race_Other',
       'race_White'], dtype=object)

In [31]:
encoded_values

array([[1., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 0., 1.],
       ...,
       [0., 0., 0., ..., 0., 0., 1.],
       [1., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 1.]], shape=(48842, 20))

In [32]:
df_encoded = pd.DataFrame(encoded_values,columns=new_cols,index=data.index)

data_final = pd.concat(
    [data.drop(columns = ['occupation','race']),df_encoded],
    axis = 1
)

In [33]:
data_final

age         workclass  fnlwgt  education  education-num  \
0       2         State-gov   77516  Bachelors             13   
1       3  Self-emp-not-inc   83311  Bachelors             13   
2       2           Private  215646    HS-grad              9   
3       3           Private  234721       11th              7   
4       1           Private  338409  Bachelors             13   
...    ..               ...     ...        ...            ...   
48837   2           Private  215419  Bachelors             13   
48838   4               NaN  321403    HS-grad              9   
48839   2           Private  374983  Bachelors             13   
48840   2           Private   83891  Bachelors             13   
48841   1      Self-emp-inc  182148  Bachelors             13   

           marital-status    relationship     sex capitalgain capitalloss  \
0           Never-married   Not-in-family    Male           1           0   
1      Married-civ-spouse         Husband    Male           0           0   
2                Divorced   Not-in-family    Male           0           0   
3      Married-civ-spouse         Husband    Male           0           0   
4      Married-civ-spouse            Wife  Female           0           0   
...                   ...             ...     ...         ...         ...   
48837            Divorced   Not-in-family  Female           0           0   
48838             Widowed  Other-relative    Male           0           0   
48839  Married-civ-spouse         Husband    Male           0           0   
48840            Divorced       Own-child    Male           2           0   
48841  Married-civ-spouse         Husband    Male           0           0   

       ... occupation_Protective-serv occupation_Sales  \
0      ...                        0.0              0.0   
1      ...                        0.0              0.0   
2      ...                        0.0              0.0   
3      ...                        0.0              0.0   
4      ...                        0.0              0.0   
...    ...                        ...              ...   
48837  ...                        0.0              0.0   
48838  ...                        0.0              0.0   
48839  ...                        0.0              0.0   
48840  ...                        0.0              0.0   
48841  ...                        0.0              0.0   

      occupation_Tech-support  occupation_Transport-moving  occupation_nan  \
0                         0.0                          0.0             0.0   
1                         0.0                          0.0             0.0   
2                         0.0                          0.0             0.0   
3                         0.0                          0.0             0.0   
4                         0.0                          0.0             0.0   
...                       ...                          ...             ...   
48837                     0.0                          0.0             0.0   
48838                     0.0                          0.0             1.0   
48839                     0.0                          0.0             0.0   
48840                     0.0                          0.0             0.0   
48841                     0.0                          0.0             0.0   

       race_Amer-Indian-Eskimo  race_Asian-Pac-Islander  race_Black  \
0                          0.0                      0.0         0.0   
1                          0.0                      0.0         0.0   
2                          0.0                      0.0         0.0   
3                          0.0                      0.0         1.0   
4                          0.0                      0.0         1.0   
...                        ...                      ...         ...   
48837                      0.0                      0.0         0.0   
48838                      0.0                      0.0         1.0   
48839                      