## Numpy array and basics


In [1]:
import numpy as np

### Create array from list

In [3]:
arr_1D = np.array([1,2,3,4,5])
print("1D array : ", arr_1D)

arr_2D = np.array([[1,2,3],[4,5,6]])
print("2D array : ",arr_2D)

1D array :  [1 2 3 4 5]
2D array :  [[1 2 3]
 [4 5 6]]


### List vs Numpy array


In [4]:
py_list = [1,2,3]
print("Python List Multiplication : ",py_list*2)

np_array = np.array([1,2,3])
print("Python array Multiplication : ",np_array*2)

Python List Multiplication :  [1, 2, 3, 1, 2, 3]
Python array Multiplication :  [2 4 6]


### Creating Array from scratch

In [9]:
zeros = np.zeros((3,4))
print("zeros array: \n",zeros)

ones = np.ones((3,4))
print("ones array: \n",ones)

full = np.full((2,2),7)
print("Full array: \n",full)

random = np.random.random((2,3))
print("random array: \n",random)

sequence = np.arange(0,10,2)
print("sequence array: \n",sequence)

zeros array: 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
ones array: 
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
Full array: 
 [[7 7]
 [7 7]]
random array: 
 [[0.81554751 0.9918402  0.29263091]
 [0.22179263 0.49237381 0.48866858]]
sequence array: 
 [0 2 4 6 8]


### Vector, Matrix and Tensor

In [11]:
vector = np.array([1,2,3])
print("vector: ", vector)

matrix = np.array([[1,2,3],[4,5,6]])
print("matrix: \n", matrix)

tensor = np.array([[[1,2],[3,4]],
                    [[5,6],[7,8]]])
print("tensor: \n", tensor)

vector:  [1 2 3]
matrix: 
 [[1 2 3]
 [4 5 6]]
tensor: 
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


### Array properties


In [13]:
arr = np.array([[1,2,3],
                [4,5,6]])
print("Shape:", arr.shape)
print("Dimension:", arr.ndim)
print("Size:", arr.size)
print("Data Type:", arr.dtype)

Shape: (2, 3)
Dimension: 2
Size: 6
Data Type: int64


### Array reshaping

In [21]:
arr = np.arange(12)
print("Original array ",arr)

reshaped = arr.reshape((3,4))
print("\n Reshaped array \n",reshaped)

flattened = reshaped.flatten()
print("\n Flattened array ",flattened)

# Returns view instead of array
raveled = reshaped.ravel()
print("\n Raveled array ",raveled)

transpose = reshaped.T
print("\n Transposed array \n",transpose)

Original array  [ 0  1  2  3  4  5  6  7  8  9 10 11]

 Reshaped array 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

 Flattened array  [ 0  1  2  3  4  5  6  7  8  9 10 11]

 Raveled array  [ 0  1  2  3  4  5  6  7  8  9 10 11]

 Transposed array 
 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
