## Numpy Array Operations

In [2]:
import numpy as np

In [14]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
print("Basic Slicing: ", arr[2:7])
print("With Step", arr[1:8:2])
print("Negative Indexing", arr[-3])

Basic Slicing:  [3 4 5 6 7]
With Step [2 4 6 8]
Negative Indexing 8


In [9]:
arr_2D = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])
print("Specific Element", arr_2D[1,2])
print("Entire Row: ",arr_2D[1])
print("Entire Column: ",arr_2D[:,1])

Specific Element 6
Entire Row:  [4 5 6]
Entire Column:  [2 5 8]


### Sorting

In [13]:
unsorted = np.array([3,1,6,4,7,5,9])
print("Sorted Array", np.sort(unsorted))

arr_2D_unsorted = np.array([[3,1],[1,2],[2,3]])
print("Sorted 2D by column \n",np.sort(arr_2D_unsorted,axis=0))
print("\n Sorted 2D by row \n",np.sort(arr_2D_unsorted,axis=1))

Sorted Array [1 3 4 5 6 7 9]
Sorted 2D by column 
 [[1 1]
 [2 2]
 [3 3]]

 Sorted 2D by row 
 [[1 3]
 [1 2]
 [2 3]]


### Filter

In [17]:
numbers = np.arange(1,11)
even_number = numbers[numbers % 2 == 0]
print("Even numbers",even_number)

Even numbers [ 2  4  6  8 10]


### Filter with mask


In [19]:
mask = numbers > 5
print("Numbers greater than 5: ",numbers[mask])

Numbers greater than 5:  [ 6  7  8  9 10]


### Fancy indexing vs np.where()

In [23]:
indices = [0,2,4]
print(numbers[indices])

where_result = np.where(numbers > 5)
print(where_result)
print("NP where", numbers[where_result])

[1 3 5]
(array([5, 6, 7, 8, 9]),)
NP where [ 6  7  8  9 10]


In [25]:
condition_array = np.where(numbers>5,numbers*2,numbers)
print(condition_array)

[ 1  2  3  4  5 12 14 16 18 20]


### Adding and Removing Data

In [27]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

combined1 = arr1 + arr2
print(combined1)

combined2 = np.concatenate((arr1,arr2))
print(combined2)

[5 7 9]
[1 2 3 4 5 6]


### Array Compatibility

In [29]:
a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.array([7,8,9])

print("Compatibilty shape", a.shape == b.shape)

Compatibilty shape True


In [32]:
original = np.array([[1,2],[3,4]])
new_row = np.array([5,6])
new_col = np.array([[7],[8]])

with_new_row = np.vstack((original,new_row))
print(original)
print(with_new_row)

with_new_col = np.hstack((original,new_col))
print(with_new_col)

[[1 2]
 [3 4]]
[[1 2]
 [3 4]
 [5 6]]
[[1 2 7]
 [3 4 8]]


In [34]:
arr = np.array([1,2,3,4,5])
deleted = np.delete(arr,2)
print("Array after deletion:",deleted)

Array after deletion: [1 2 4 5]
